### ISSUE TITLE
.gitignore file it's created without .

### ISSUE THREAD

**Issue by AndresBetancourt-Dev** [jherr/create-mf-app#19]
When creating an app with create-mf-app the .gitignore file it's created without a . 

![image](https://user-images.githubusercontent.com/65095693/144349129-ea874522-8a0b-4b31-973b-163e56df8cba.png)

This causes that my project now has 10K in file changes.

![image](https://user-images.githubusercontent.com/65095693/144349231-b49783a1-762e-4ed5-9493-4b817106b1ef.png)

I have no problem changing file extension name by myself but it's like a little bug
![image](https://user-images.githubusercontent.com/65095693/144349842-48402b1b-1def-4780-8b92-eac771160875.png)

**Comment by jherr** [comment]
Which configuration was this? And which operating system? Were there any error messages during the run?

**Comment by AndresBetancourt-Dev** [comment]
Windows 10.
This is the configuration 
![image](https://user-images.githubusercontent.com/65095693/144354136-3b6680d8-3f64-4fd0-93e1-358d3a439a46.png)

Tried again and happened the same
![image](https://user-images.githubusercontent.com/65095693/144354182-be2f4c1b-5794-4104-879e-6061d44b865f.png)

**Comment by jherr** [comment]
Can you try again with version 1.0.14?

**Comment by AndresBetancourt-Dev** [comment]
![image](https://user-images.githubusercontent.com/65095693/144362787-c51c63ec-3dd1-4489-a711-b5328ca3a556.png)
![image](https://user-images.githubusercontent.com/65095693/144363077-b50ab529-3618-43b1-ba2f-132878b83ca5.png)

Same

**Comment by jherr** [comment]
Figured it out, turns out it wasn't Windows specific at all. Should be good now with 1.0.15.

**Comment by AndresBetancourt-Dev** [comment]
Very much appreciated jack wonderful tool, will keep using it for further projects 
![image](https://user-images.githubusercontent.com/65095693/144500462-91bfb135-2a7d-490e-bca6-97cf304f5ea2.png)
