### ISSUE TITLE
Using local package causes webpack build errors 

### ISSUE THREAD

**Issue by dafreaki** [jherr/create-mf-app#22]
Current Config:

package.json
`"dependencies": {`
`    "@babel/runtime": "^7.13.10",`
`    "local-component": "file:local-component-0.1.0.tgz",`
`    "react": "^17.0.2",`
`    "react-dom": "^17.0.2",`
`}`

webpack.config.js

`plugins: [`
 `   new ModuleFederationPlugin({`
`      name: "module1",`
`      filename: "remoteEntry.js",`
`      remotes: {module2:'module2@http://localhost:8001/remoteEntry.js'},`
`      exposes: {},`
`      shared: {`
`        ...deps,`

This  causes
`Module not found: Error: Can't resolve 'file:local-component-0.1.0.tgz'`

Workaround
webpack.config.js
`plugins: [`
`    new ModuleFederationPlugin({`
`      name: "module1",`
`      filename: "remoteEntry.js",`
`      remotes: {module2:'module2@http://localhost:8001/remoteEntry.js'},`
`      exposes: {},`
`      shared: {`
`        ...deps,`
`    "local-component": {},`

**Comment by jherr** [comment]
Not sure what do about this one. If that's the way you want to include a package then, yes, you'd have to make this alteration, but I think this is fairly uncommon thing to do.
