### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by dexkode4** [jherr/create-mf-app#36]
Jest not working because of the above error
I'm using typescript template

**Comment by jherr** [comment]
What's the error? There is nothing above. Also, please don't post a screenshot. Post the text of the error you are seeing. Screenshots aren't helpful.

**Comment by dexkode4** [comment]
I mean the error in the title of this issue
**SyntaxError: Cannot use import statement outside a module**
I've spent hours on this error, please help

**Comment by jherr** [comment]
Unless the `create-mf-app` created a project that immediately resulted in this error, this is not a bug on this generator.

I'm sorry you're running into issues. If you like you can join my Discord server (https://discord.gg/nGxhQ3SY) then read the #rules carefully and post a question that can be answered in an appropriate channel.

**Comment by dexkode4** [comment]
Thanks
FYI I'm using **create-mf-app** 
was wondering if there was a setup already I could just apply to my situation.

**Comment by jherr** [comment]
Honestly, `create-mf-app` was built to produce prototype code for Module Federation setups. It wasn't meant to bootstrap production apps. Each one of these frameworks have starter kits that are designed for that purpose. I wouldn't be trying to use Jest with `create-mf-app` I would instead use something like Create React App (CRA) that has unit testing built into it.

**Comment by dexkode4** [comment]
ahh I see, thank you again
