### ISSUE TITLE
Problem when creating a react with typescript tailwind 

### ISSUE THREAD

**Issue by hzprog** [jherr/create-mf-app#4]
### Problem when creating a react with typescript tailwind 

I was following your tutorial on youtube the title is : **GraphQL/JWT Speed Run with Refresh Tokens** link : https://youtu.be/QChEaOHauZY

So when i was following a long with the video i used `npx create-mf-app`  then after that i used the name **host** for the application then i selected **Application** for the project type,  then for the port i used the default one **8080** and for the framework i used **react** , language **Typescript** , CSS : **Tailwind** then i got the message :

```
npx: installed 71 in 12.809s
? Pick the name of your app: host
? Project Type: Application
? Port number: 8080
? Framework: react
? Language: typescript 
? CSS: Tailwind

Your 'host' project is ready to go.

Next steps:

▶️ cd host
▶️ npm install
▶️ npm start

node:11884) UnhandledPromiseRejectionWarning: TypeError: fs.rmSync is not a function
    at module.exports (C:\Users\ezzin\AppData\Roaming\npm-cache\_npx\11884\node_modules\create-mf-app\src\index.js:71:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
and after that if i tried to ignore the error and to run **npm install** or **yarn** on the new directory created i got this :

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid name: "{{NAME}}"
npm WARN host No description
npm WARN host No repository field.
npm WARN host No README data
npm WARN host No license field.

up to date in 0.7s
found 0 vulnerabilities
```

So i wanted to report it to you and that's the folder generated 

[host.zip](https://github.com/jherr/create-mf-app/files/7446273/host.zip)
 
I am using Windows 10 64 bits in a dell xps laptop

**Comment by jherr** [comment]
This should be fixed. We moved to `unlinkSync`.
