### ISSUE TITLE
Please Add a basic Angular 14 template for this 🙏🥺

### ISSUE THREAD

**Issue by FlashAmarillo** [jherr/create-mf-app#41]
we need to add Angular to tyhe list of frameworks

**Comment by jherr** [comment]
Then get angular to make it a lot easier to install angular **without** the CLI. No other framework **requires** a CLI. I tried talking with them about it and the answer was; You shouldn't ever be doing anything other than Angular, so you should just make your app in Angular and that's it.

**Comment by FlashAmarillo** [comment]
angular is an excellent framework, but it is complicated to use it as a microfront together with other frameworks, for example, a monolith in angular 14 and a microfront in react 18, the webpack configurations can be a headache.

**Comment by jherr** [comment]
Can you address my statement? All your saying is that you really really want me to add angular. Fair, but I'm telling you that I'd have to create an entirely different path to add Angular and even then I'm not sure I can do it because it involves going through the CLI.
