### ISSUE TITLE
mismatched template path for API Server

### ISSUE THREAD

**Issue by Godeing** [jherr/create-mf-app#47]
I got this error below when trying to create an api server:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/12955630/233912867-c18ae516-8b53-4c8a-b7b5-0bde6ee2bdfb.png">

I think it's the mismatched type name here that cause this
https://github.com/jherr/create-mf-app/blob/1acb8c42e3587ea70c52549f38cdab108a3ead2c/src/index.ts#L83-L87

`tempDir` here is only transform to lowercase, which doesn't match the `server` directory in templates

**Comment by irvingvjuarez** [comment]
The problem persists. when the "API Server" option is selected, that very same error is showing up.
It would not be a better solution to add a "try catch" or .catch to handle the error, just as the error tells?

**Comment by jherr** [comment]
I've published a new version, 1.0.18, that has the fix.
