### ISSUE TITLE
replacements not working for vue3 with ts

### ISSUE THREAD

**Issue by paddomanno** [jherr/create-mf-app#54]
Choosing these options leaves the replacements in the source code instead of replacing them. 

This is the generated App.vue:

```vue
<template>
  <div class="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>
```

Command and settings used:

```bash
> npx create-mf-app
? Pick the name of your app: name
? Project Type: Application
? Port number: 8080
? Framework: vue3
? Language: typescript
? CSS: CSS
```

This is in create-mf-app v1.0.18

**Comment by souyang** [comment]
I cannot reproduce this issue via create-mf-app v1.0.18 and follow the exact same steps. 
@paddomanno  Did you try `npm cache clean --force &&npx create-mf-app` from your end?

Below is the generated code in App.vue from my end. 
```code
<template>
  <div class="container">
    <div>Name: name</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>
```
@paddomanno Did you see any error in the logs after generation?

**Comment by paddomanno** [comment]
@souyang Seems like I cannot reproduce this issue either. I tried a couple of times (without `npm cache clean`) and it worked just fine. Maybe it was a one-off error. If it happens again, I will check the logs. For now I guess I can close the issue.
