### ISSUE TITLE
Problem with libraries

### ISSUE THREAD

**Issue by narcecl** [jherr/create-mf-app#56]
Hi, im using the defaul installation for a project:
Name: test
Framework: react
Language: TypeScript
CSS: Empty CSS

But i'm having this error while i'm trying to import a component from a private library.

ERROR in ./node_modules/@my-library/package.json 2:10
Module parse failed: Unexpected token (2:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

>  "name": "@my-library",
 "description": "description",
"version": "1.1.6",

Any idea or webpack configuration to solve the issue?

**Comment by jherr** [comment]
Something is trying to load the package.json as source and the simple webpack configuration created by create-mf-app doesn't support loading JSON. create-mf-app is not meant to be used as a starting point for production applications. it's a helper to create test applications to check out possible remote/host architectures using Module Federation.

**Comment by narcecl** [comment]
@jherr the starter point from my library is the package.json, wich export the index file (library itself).
Is there a way to workaround this error or create-mf-app is not mean to do this kind of stuff?

**Comment by jherr** [comment]
I don't understand what "starter point from my library is the package.json" means. The "starter point" for a library is defined using the `main` key and points to an `index.js` file (usually) or a `src/index.js`. It sounds like you are trying to do some funky stuff and yeah, `create-mf-app` is not designed for that.

**Comment by narcecl** [comment]
Yeah, the "main" key is defined by the package.json, so i'm assuming that the default file is package.json and it redirects to the 'src/index.js", defined by the "main" key, but the error itself explains that can't handle the package.json file.

**Comment by jherr** [comment]
No, some code is trying to import the package.json itself. It's possible it has something to do with the name of your package. The format is usually "library-name" or "@org-name/library-name". Not "@library-name" as you have it. You might try something like "@nercecl/my-library".

**Comment by narcecl** [comment]
Yes, the name is `@org-name/components`, the other name was an example. But with that i may figure it out what went wrong.

**Comment by jherr** [comment]
Ok. Reading JSON files using `import` or `require` is fine, including `package.json`. But you need to add the JSON loader to the webpack configuration to do that. No Module Federation example that I created loaded JSON, so I didn't add it.

Please be very aware that Module Federation can **NOT** import JSON, CSS, images, etc. It can **ONLY** import JavaScript.

**Comment by narcecl** [comment]
Thank you very much, I was exporting a constant with the current version value `package.json`, so without a json loader it was failing. The error had nothing to do with create-mf-app.
