### ISSUE TITLE
[Feature] NextJS Projects support

### ISSUE THREAD

**Issue by impondesk** [jherr/create-mf-app#63]
Would be great If we can support nextJS MFE compatibility out of same plugin.

**Comment by calvinn-scribd** [comment]
Agreed; especially with Next.js V14; and React V19. Is this already in the works with an ETAs?

**Comment by jherr** [comment]
There is no NextJS App Router plugin or compatible version AFAIK. Nor do I know of any in the works.

**Comment by calirails** [comment]
Thanks for all the awesome tutorials and repos @jherr. MFEs are hard to get up and running in some cases. I am eager to develop a MFE based solution on Next.js v14 with SSR and SSG and was hoping to use this very helpful CLI or some alternative you can steer me to.

Several questions to help me get oriented.

> There is no NextJS App Router plugin or compatible version AFAIK
Is the **App Router plugin** a requirement for Next JS to work with Module Federation or is the plugin a specific component required to make the CLI work? 

I've tried working through this myself and have run into three errors and hope you can shed some light on so I can reproduce the tutorial on my Macbook Air on M2 processor.

**1. Tailwind|CSS problem display problem on Host App**
On the running remote app with the Counter, I can see the Counter with some basic background and padding but the host application doesn't display correctly despite having the Tailwind classes. I've verified the head element has the <style> tag with the same Tailwind utility classes. I've also shut down and restarted via `yarn start` with all the latest changes. Here's a side by side.
![image](https://github.com/jherr/create-mf-app/assets/942698/2531067f-1743-4280-9bb9-e66acc816677)
_Aside: this host here is just the Solid Host running on port 3000_

**2. React Host with Counter Wrapper component**
The code for the CounterWrapper is as you have outlined but results in the following compilation error. 
<img width="896" alt="image" src="https://github.com/jherr/create-mf-app/assets/942698/974b00a7-508a-4842-a81a-f4ead8f83371">

Here is the code for the CounterWrapper but with the render function commented out and swapped for a hardcoded snippet to isolate the error.
```
import { createSignal  } from "solid-js";
import { render } from "solid-js/web";
import Counter from "./Counter"
import "./index.scss";

export default () => {
  // Intended code but it breaks the compiler
  // render(Counter, element);
  return(
    <div class="mt-10 text-3xl mx-auto max-w-6xl">
      Counter Wrapper says Hello
    </div>
  );
}
```

My objective is to build a Microfrontends on NextJS v14 with SSR and SSG. I have attempted many of your YouTube play list on Microfrontends and have run into various version problems with my local Next and/or React, Node runtimes. **Do you have an updated video on how to get up and running with Next.js v14 to support SSR and SSG modes?**

**Alternatives I have attempted**
a) If I try to use the latest create-next-app CLI; and follow the guide such as this one [here](https://alibek.dev/micro-frontends-with-nextjs-and-module-federation); I immediately run into the error: `ReferenceError: require is not defined in ES module scope, you can use import instead` that stems from this next.config.mjs line 
```
file: next.config.mjs
const { NextFederationPlugin } = require('@module-federation/nextjs-mf');
// import instead?
// import { NextFederationPlugin } from '@module-federation/nextjs-mf'
```

Changing to the use of `import` as seen in the commented line shown above results in this new error.
```
yarn dev
yarn run v1.22.19
$ next dev
node:internal/modules/esm/resolve:853
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@module-federation/nextjs-mf' imported from /Users/calvinnguyen/projects/web/temp/my-app/next.config.mjs
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
I've tried renaming the next.config.mjs file to next.config.js with the use of `const { NextFederationPlugin } = require('@module-federation/nextjs-mf');` but got another error. 



b) I've tried this ['authoritative' repo here](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v14) but get this compilation error alluding to `swc .... not being compatible` when trying to yarn start to run the site. I'll go to that repository and file a new issue for this observation if it hasn't been reported.

**Comment by jherr** [comment]
The requirements are what you decide that you want to do. AFAIK the App Router is currently incompatible with Module Federation and there is nothing in the works to make it compatible. The repo you point to shows a Pages router implementation.

"Do you have an updated video on how to get up and running with Next.js v14 to support SSR and SSG modes?" No. As I say, the App Router isn't compatible with MF that I know of.

"SSR and SSG modes" I've never personally tried to get SSR working with MF. I know that it has been done but I haven't had a need for that in any project I've worked on. And to me, SSG + MF, makes no sense at all.

As for the CSS issues. Module Federation used to not be capable of exporting CSS. That has changed. I've gotten CSS export to work with the Vite plugin as well as the Webpack plugin. I'm not sure what the issue here is though.

Sorry I'm not of more help here. You probably want to talk with Zack Jackson directly about this. He's recently offered to directly support anyone, so you should take him up on that.
