### ISSUE TITLE
add .gitignore to templates bug

### ISSUE THREAD

**Issue by JonathanDagan** [jherr/create-mf-app#7]
### The code:
_src\index.js 39_
```js
if (type === "Library") {
  await ncp(path.join(__dirname, `../templates/${tempDir}/typescript`), name);
}

if (type === "Server") {
  replacements.PORT = port;

  await ncp(
    path.join(__dirname, `../templates/${tempDir}/${framework}`),
    name
  );
}

if (type === "Application") {
  await ncp(
    path.join(__dirname, `../templates/${tempDir}/${framework}/base`),
    name
  );
  await ncp(
    path.join(__dirname, `../templates/${tempDir}/${framework}/${lang}`),
    name
  );
```

### create-mf-app version: 1.0.11
I'm using a windows 10 machine and the following specs:

- node version: v16.7.0
- npm version: 8.1.4

I have run the command with both ps and bash (git bash) and it doesn't work
I have both run it straight with npx and installed it globally and only then with npx

I'm running the command in an additional drive (`F:\`) which I don't think it should impact. I have run the `ncp()` command through node interactive mode (`node -i`) and it has worked successfully.

## Summary:

I'm left baffled since the rest of the folder contents are copied just fine and can't seem to nail it down to the problem. The only thing I'm going off with is that it might have something to do with .gitignore being a . file (hidden file) since it is the only missing file from the MF app

**Comment by JonathanDagan** [comment]
I'm working on this issue and creating a PR for this soon

**Comment by JonathanDagan** [comment]
# Found the source of the bug!🎉

Looking into the installed package at the global node_modules directory, the create-mf-app node_module at `C:\Users\{user}\AppData\Roaming\npm\node_modules\create-mf-app` doesn't seem to have the .gitignore files in the templates.

This is apparently a known [issue](https://github.com/npm/npm/issues/3763) with npm and will need a fix on our level, ill submit a PR request soon hopefully :)

I'll work on a solution where for each app at the end it will rename the file from `gitignore` to `.gitignore` since this seems to be the common solution in the [issue](https://github.com/npm/npm/issues/3763) thread. If you think of other more elegant solutions I would love to discuss them.

**Comment by opauloh** [comment]
Thanks, @JonathanDagan, I just pushed a repository with `node_modules` because I didn't notice `.gitignore` was missing!

@jherr looking forward to get this one merged!

**Comment by JonathanDagan** [comment]
# ✅Bug Fixed!🎉
#8 has been merged so I'm closing this issue :)
