### ISSUE TITLE
[BUG] 'NODE_ENV' is not recognized (RSPACK) 

### ISSUE THREAD

**Issue by CosmeValera** [jherr/create-mf-app#70]
## 🐛 Problem
While using the Rspack version with any of the languages, when I try to execute `npm start` the following problem arises:
```bash
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
```
## 🧠 Thought process
This is a real life example of the error showed above:
![image](https://github.com/jherr/create-mf-app/assets/80126839/895bd46e-da0a-4d9b-a8aa-cee76bb62712)

`package.json`: 
```json
{
  ...
  "scripts": {
    "build": "NODE_ENV=production rspack build",
    "build:dev": "NODE_ENV=development rspack build",
    "build:start": "cd dist && rspack serve",
    "start": "NODE_ENV=development rspack serve"
  },
  ...
}
```

---

However if I remove the `NODE_ENV` part in the start script this error does not appear anymore:
```json
{
  ...
  "scripts": {
    "build": "NODE_ENV=production rspack build",
    "build:dev": "NODE_ENV=development rspack build",
    "build:start": "cd dist && rspack serve",
    "start": "rspack serve"
  },
  ...
}
```
![image](https://github.com/jherr/create-mf-app/assets/80126839/a3e19484-574d-47b6-b5e9-e0ba11c4aea4)
There is a configuration error, but the project is correctly displayed in the browser:
![image](https://github.com/jherr/create-mf-app/assets/80126839/01117bb0-1faf-4a93-8d89-c8c7163250f6)

## 🤠 Solution
I don't know much about Rspack, however my instant suggestion would be to simply remove the `NODE_ENV=development` and `NODE_ENV=production` from the scripts, so it at least works out of the box. However, it would be very helpful if someone that knew a bit about rspack could guide a little in this topic about what the correct approach for this would be. 💓💓

**Comment by CosmeValera** [comment]
@ScriptedAlchemy

**Comment by zmzlois** [comment]
It does shows as if this is a bug but I believe it is not. 

Not sure about other frameworks but React conduct additional checks when `NODE_ENV=development` and setting it to `NODE_ENV=production` will improve performance.
