### ISSUE TITLE
Production Ready steps

### ISSUE THREAD

**Issue by marcomanzi** [jherr/create-mf-app#76]
I would love to understand what would be the best approach to make a starter that is also production ready. 
What is it missing?

**Comment by jherr** [comment]
These aren't designed to be deployed in production. They are missing lots of the basics (unit tests, e2e tests, logging, etc.) This CLI app is meant to build applications that you can use to test different Module Federation architectures. You are free to use them as a starting point to eventually create a production app, but that's not the point of this CLI.
